export type Profile = { name:string; email:string; phone:string; location:string; targets:string; geography:string; cpa:'unconfirmed'|'completed'|'in-progress'; summary:string; resumeText?:string; linkedin?:string };
export type Job = { id:string; title:string; company:string; location:string; url:string; description:string; salary:string; source:string; published:string };
export type Automation = {enabled:boolean;autoApply:boolean;profileConfirmed:boolean;telegramEnabled:boolean;intervalHours:number;dailyLimit:number;roles:string;locations:string;lastRun:string|null;lastError:string;attempts:{id:string;day:string;outcome:string}[]};
export const defaultAutomation:Automation={enabled:false,autoApply:false,profileConfirmed:false,telegramEnabled:false,intervalHours:6,dailyLimit:15,roles:'accountant,accounting,finance,payroll,bookkeeper',locations:'*',lastRun:null,lastError:'',attempts:[]};
export type Application = Job & {applicationEmail?:string;recipientConfirmed?:boolean;eligibilityConfirmed?:boolean; status:'Draft'|'Ready'|'Applied'|'Interview'|'Offer'|'Closed'|'Needs review'; letter:string; notes:string; created:string; updated:string; followUp:string };
export type Desk = { profile:Profile; applications:Application[];automation?:Automation };
export const initialProfile:Profile = {name:'Clinton Ouma Ooremo',email:'clintoniremo@gmail.com',phone:'+254 745 313 247',location:'Nairobi, Kenya',targets:'Accountant, Finance Officer, Finance and Administration Manager, Payroll Accountant, ERP Finance',geography:'Kenya; remote roles open to Kenya',cpa:'unconfirmed',summary:'I am a finance and administration professional with a Bachelor of Business Administration (Accounting) from the University of Eastern Africa, Baraton. My experience covers financial reporting, budgeting, cash-flow management, accounts payable and receivable, payroll, statutory compliance, NGO reporting and accounting systems.'};
export const evidence = [
 {skill:'Financial reporting',pattern:'financial report|financial statement|month.end|general ledger',claim:'I have prepared management reporting packs, financial statements and cash-flow reports, with variance analysis to support management decisions.'},
 {skill:'Budgeting & forecasting',pattern:'budget|forecast|financial model',claim:'My finance responsibilities include annual budgeting, cash-flow forecasting, cost analysis and financial modelling.'},
 {skill:'Payroll',pattern:'payroll|salary processing',claim:'At Nasio Trust Kenya and in my subsequent finance roles, I have processed payroll and prepared statutory deductions and submissions.'},
 {skill:'Tax & statutory compliance',pattern:'tax|compliance|vat|paye|statutory',claim:'I have handled Kenyan statutory returns and submissions, including VAT, PAYE and withholding tax, alongside tax and customs work at the Kenya Revenue Authority.'},
 {skill:'Accounts payable & receivable',pattern:'payable|receivable|reconcil|debtor|collections',claim:'My work includes invoicing, supplier reconciliations, debtor follow-up, aging reports and cash-flow management.'},
 {skill:'QuickBooks',pattern:'quickbooks',claim:'I have used QuickBooks for transaction posting, inventory accounting and financial reporting.'},
 {skill:'Zoho Books',pattern:'zoho',claim:'I have used Zoho Books to maintain accounting records and support daily finance operations.'},
 {skill:'Excel',pattern:'excel|spreadsheet',claim:'My accounting work is supported by advanced Microsoft Excel skills and formal training in accounting packages.'},
 {skill:'NGO & donor reporting',pattern:'ngo|donor|grant|non.profit',claim:'At Nasio Trust Kenya, I prepared donor project reports, fund reports and hospital financial statements, including presentations to donors.'},
 {skill:'ERP & systems',pattern:'erp|systems|software|technology',claim:'Alongside my finance work, I contributed to the Zuriel Solutions platform, translating accounting and operational workflows into requirements for rental, fleet and bookkeeping modules.'}
];
export function matchJob(job:Job){ const text=job.title+' '+job.description; return evidence.filter(e=>new RegExp(e.pattern,'i').test(text)); }
export function draftLetter(job:Job,profile:Profile){ const selected=matchJob(job).slice(0,4); const degree=/bachelor/i.test(profile.summary)?'':'I hold a Bachelor of Business Administration in Accounting from the University of Eastern Africa, Baraton.'; const cpa=profile.cpa==='completed'?' I have completed the CPA qualification.':profile.cpa==='in-progress'?' I am pursuing the CPA qualification.':''; return `Dear Hiring Team,\n\nI am applying for the ${job.title} position at ${job.company}. ${profile.summary}\n\n${selected.length?selected.map(s=>s.claim).join(' '):'My background includes managing finance operations, maintaining accounting records and supporting financial reporting across technology, NGO and government settings.'}\n\n${degree}${cpa}\n\nI would welcome the opportunity to discuss how my finance and systems experience could contribute to your team. Thank you for considering my application.\n\nKind regards,\n${profile.name}\n${profile.email}\n${profile.phone}`; }
export function safeUrl(value:string){try{const u=new URL(value);return u.protocol==='https:'||u.protocol==='http:'?u.href:''}catch{return ''}}

